set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" color scheme
Plugin 'nanotech/jellybeans.vim'

" status line
Plugin 'itchyny/lightline.vim'

" NERDTree
"Plugin 'scrooloose/nerdtree'

" Black
Plugin 'psf/black'

" Markdown
Plugin 'plasticboy/vim-markdown'
Plugin 'kannokanno/previm'
Plugin 'tyru/open-browser.vim'

call vundle#end()
filetype plugin indent on


" 一般
"文字コードをUFT-8に設定
set fenc=utf-8
" バックアップファイル
set backup
set backupdir=$TEMP\Vim\backup,$TEMP
" スワップファイルを作らない
set noswapfile
set directory=$TEMP\Vim\swap,$TEMP
" アンドゥファイル
set undofile
set undodir=$TEMP\Vim\undo,$TEMP
" viminfoファイル
let s:viminfo_path=substitute(expand('$TEMP\Vim\_viminfo'), '\\', '\\\\', 'g')
execute 'set viminfo+=n' . s:viminfo_path

" 編集中のファイルが変更されたら自動で読み直す
set autoread
" 開いたファイルの場所をカレントディレクトリにする
set autochdir
" バッファが編集中でもその他のファイルを開けるように
set hidden
" 入力中のコマンドをステータスに表示する
set showcmd
" 無名レジスタに入るデータを、*レジスタにも入れる
set clipboard+=unnamed

" 見た目系
" 行番号を表示
set number
" ビープ音を可視化
"set visualbell
" ベル音を鳴らさないようにイベントを指定
set belloff=all
" コマンドラインの補完
set wildmode=list:longest
" 長い行を折り返さないで表示
set nowrap
" 折り返し時に表示行単位での移動できるようにする
nnoremap j gj
nnoremap k gk
" シンタックスハイライトの有効化
syntax enable


" Tab系
" 不可視文字を可視化(タブが「?-」と表示される)
set list listchars=tab:\?\-
" Tab文字を半角スペースにする
set expandtab
" 行頭以外のTab文字の表示幅（スペースいくつ分）
set tabstop=4
" 行頭でのTab文字の表示幅
set shiftwidth=4
" インデントはスマートインデント
set smartindent
" 改行時に前の行のインデントを継続
set autoindent


" 検索系
" 検索文字列入力時に順次対象文字列にヒットさせる
set incsearch
" 検索語をハイライト表示
set hlsearch
" ESC連打でハイライト解除
nmap <Esc><Esc> :nohlsearch<CR><Esc>


" キーバインド
"noremap <C-n> :NERDTreeToggle<CR>
noremap <C-Tab> :bnext<CR>
noremap <C-S-Tab> :bprev<CR>
noremap <silent> <C-p> :PrevimOpen<CR>


" JSONの整形(jq)
set rtp+=~/.vim/bundle/Vundle.vim
let $PATH .= ';' . $HOME . '\.vim\tools'
command! Jq %!jq-win64


" プラグイン系
" vim-markdown
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_auto_insert_bullets = 0
let g:vim_markdown_new_list_item_indent = 0

" previm
autocmd BufRead,BufNewFile *.md set filetype=markdown

" open-browser.vim
let g:netrw_nogx = 1 " disable netrw's gx mapping.
nmap gx <Plug>(openbrowser-smart-search)
vmap gx <Plug>(openbrowser-smart-search)

" black
let g:black_virtualenv = $HOME . '\.venvs\black37'

