set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" color scheme
Plugin 'nanotech/jellybeans.vim'

" status line
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" NERDTree
Plugin 'scrooloose/nerdtree'

" Advanced icons
Plugin 'ryanoasis/vim-devicons'

call vundle#end()
filetype plugin indent on


" 一般
"文字コードをUFT-8に設定
set fenc=utf-8
" バックアップファイル
set backup
set backupdir=$TEMP\Vim\backup,$TEMP
" スワップファイルを作らない
set noswapfile
set directory=$TEMP\Vim\swap,$TEMP
" アンドゥファイル
set undofile
set undodir=$TEMP\Vim\undo,$TEMP
" 編集中のファイルが変更されたら自動で読み直す
set autoread
" 開いたファイルの場所をカレントディレクトリにする
set autochdir
" バッファが編集中でもその他のファイルを開けるように
set hidden
" 入力中のコマンドをステータスに表示する
set showcmd
" 無名レジスタに入るデータを、*レジスタにも入れる
set clipboard+=unnamed

" 見た目系
" 行番号を表示
set number
" ビープ音を可視化
"set visualbell
" コマンドラインの補完
set wildmode=list:longest
" 長い行を折り返さないで表示
set nowrap
" 折り返し時に表示行単位での移動できるようにする
nnoremap j gj
nnoremap k gk
" シンタックスハイライトの有効化
syntax enable


" Tab系
" 不可視文字を可視化(タブが「?-」と表示される)
set list listchars=tab:\?\-
" Tab文字を半角スペースにする
set expandtab
" 行頭以外のTab文字の表示幅（スペースいくつ分）
set tabstop=4
" 行頭でのTab文字の表示幅
set shiftwidth=4
" インデントはスマートインデント
set smartindent
" 改行時に前の行のインデントを継続
set autoindent


" 検索系
" 検索文字列入力時に順次対象文字列にヒットさせる
set incsearch
" 検索語をハイライト表示
set hlsearch
" ESC連打でハイライト解除
nmap <Esc><Esc> :nohlsearch<CR><Esc>


" キーバインド
noremap <C-n> :NERDTreeToggle<CR>
noremap <C-Tab> :bnext<CR>
noremap <C-S-Tab> :bprev<CR>


